# This file is copied to spec/ when you run 'rails generate rspec:install'
ENV["RAILS_ENV"] ||= 'test'
require File.expand_path("../../config/environment", __FILE__)
require 'rspec/rails'
require 'shoulda/matchers'
require 'email_spec'
require 'email_spec/rspec'
require 'fakeweb'
require 'webmock/rspec'

# Requires supporting ruby files with custom matchers and macros, etc, in
# spec/support/ and its subdirectories. Files matching `spec/**/*_spec.rb` are
# run as spec files by default. This means that files in spec/support that end
# in _spec.rb will both be required and run as specs, causing the specs to be
# run twice. It is recommended that you do not name files matching this glob to
# end with _spec.rb. You can configure this pattern with with the --pattern
# option on the command line or in ~/.rspec, .rspec or `.rspec-local`.
Dir[Rails.root.join("spec/support/**/*.rb")].each { |f| require f }

# Checks for pending migrations before tests are run.
# If you are not using ActiveRecord, you can remove this line.
ActiveRecord::Migration.maintain_test_schema!

WebMock.allow_net_connect! 

# currencies: 10, 100, 101, 105

# https://api.mycurrency.com/authorized_currencies/<ID>
FakeWeb.register_uri(:get, "https://api.mycurrency.com/authorized_currencies/1", body: '{"data":{"id":"1","type":"currencies","attributes":{"issuer-id":3,"issuer-user-id":3,"issuer-user-name":"Kian","issuer-user-avatar-url":"/system/users/avatars/000/000/003/original/avatar.jpg?1568607042","issuer-public-currency-holding-id":1,"burn-rate":0,"daily-burn-rate":"0.0","store-count":0,"listing-count":0,"product-count":0,"name":"Kian Dollar","description":"The first currency created on MyCurrency\n! Check the creation date.","created-at":"2019-09-15T21:14:17.830-07:00","updated-at":"2019-09-16T19:38:19.756-07:00","get-icon-url":"/system/currencies/icons/000/000/001/original/currency.jpg?1568607257","number-of-reviews":0,"average-score":null,"public-amount-atomic":0,"public-currency-holding-id":null,"private-amount-atomic":0,"private-currency-holding-id":null,"total-amount-atomic":0,"number-of-burn-rate-changes":1,"number-public-currency-holdings":1,"next-daily-burn-amount":"0.0","timedate-of-last-private-tx":null,"amount-of-last-private-tx":null,"timedate-of-last-public-tx":null,"amount-of-last-public-tx":null,"private-burn-amount-atomic":0,"public-burn-amount-atomic":0,"total-burn-amount-atomic":0}}}')

FakeWeb.register_uri(:get, "https://api.mycurrency.com/authorized_currencies/2", body: '{"data":{"id":"2","type":"currencies","attributes":{"issuer-id":2,"issuer-user-id":2,"issuer-user-name":"Amin","issuer-user-avatar-url":"/system/users/avatars/000/000/002/original/avatar.jpg?1568543223","issuer-public-currency-holding-id":2,"burn-rate":700,"daily-burn-rate":"0.000198805","store-count":1,"listing-count":0,"product-count":1,"name":"Amin Credit","description":"one dollars worth of credit for purchases from my store","created-at":"2019-09-15T21:45:53.821-07:00","updated-at":"2020-03-15T01:41:03.937-07:00","get-icon-url":"/system/currencies/icons/000/000/002/original/currency.jpg?1584261663","number-of-reviews":0,"average-score":null,"public-amount-atomic":0,"public-currency-holding-id":null,"private-amount-atomic":54146673457723,"private-currency-holding-id":160,"total-amount-atomic":54146673457723,"number-of-burn-rate-changes":4,"number-public-currency-holdings":3,"next-daily-burn-amount":"10764629416.762621015","timedate-of-last-private-tx":"2020-03-11T06:06:36.334-07:00","amount-of-last-private-tx":54330000000000,"timedate-of-last-public-tx":null,"amount-of-last-public-tx":null,"private-burn-amount-atomic":183326542277,"public-burn-amount-atomic":0,"total-burn-amount-atomic":183326542277}}}')

FakeWeb.register_uri(:get, "https://api.mycurrency.com/authorized_currencies/3", body: '{"data":{"id":"3","type":"currencies","attributes":{"issuer-id":4,"issuer-user-id":4,"issuer-user-name":"Don","issuer-user-avatar-url":"/system/users/avatars/000/000/004/original/avatar.jpg?1568616946","issuer-public-currency-holding-id":3,"burn-rate":500,"daily-burn-rate":"0.00014052","store-count":1,"listing-count":0,"product-count":1,"name":"CryptoStore Dollars","description":"store credit for my crypto asset store","created-at":"2019-09-15T23:59:22.636-07:00","updated-at":"2019-09-15T23:59:22.636-07:00","get-icon-url":"/system/currencies/icons/000/000/003/original/currency.jpg?1568617162","number-of-reviews":0,"average-score":null,"public-amount-atomic":0,"public-currency-holding-id":null,"private-amount-atomic":111758926010875,"private-currency-holding-id":154,"total-amount-atomic":111758926010875,"number-of-burn-rate-changes":0,"number-public-currency-holdings":3,"next-daily-burn-amount":"15704364283.048155","timedate-of-last-private-tx":"2020-03-10T09:08:05.259-07:00","amount-of-last-private-tx":12370000000000,"timedate-of-last-public-tx":null,"amount-of-last-public-tx":null,"private-burn-amount-atomic":311073989125,"public-burn-amount-atomic":0,"total-burn-amount-atomic":311073989125}}}')

FakeWeb.register_uri(:get, "https://api.mycurrency.com/authorized_currencies/4", body: '{"data":{"id":"4","type":"currencies","attributes":{"issuer-id":3,"issuer-user-id":3,"issuer-user-name":"Kian","issuer-user-avatar-url":"/system/users/avatars/000/000/003/original/avatar.jpg?1568607042","issuer-public-currency-holding-id":7,"burn-rate":0,"daily-burn-rate":"0.0","store-count":0,"listing-count":0,"product-count":0,"name":"USD Tracker","description":"Is worth exactly $1 USD","created-at":"2019-09-16T19:43:22.229-07:00","updated-at":"2019-09-16T19:43:22.229-07:00","get-icon-url":"/system/currencies/icons/000/000/004/original/currency.jpg?1568688202","number-of-reviews":0,"average-score":null,"public-amount-atomic":0,"public-currency-holding-id":null,"private-amount-atomic":0,"private-currency-holding-id":null,"total-amount-atomic":0,"number-of-burn-rate-changes":0,"number-public-currency-holdings":0,"next-daily-burn-amount":"0.0","timedate-of-last-private-tx":null,"amount-of-last-private-tx":null,"timedate-of-last-public-tx":null,"amount-of-last-public-tx":null,"private-burn-amount-atomic":0,"public-burn-amount-atomic":0,"total-burn-amount-atomic":0}}}')

FakeWeb.register_uri(:get, "https://api.mycurrency.com/authorized_currencies/10", body: '{"data":{"id":"10","type":"currencies","attributes":{"issuer-id":17,"issuer-user-id":17,"issuer-user-name":"Anza","issuer-user-avatar-url":"/system/users/avatars/000/000/017/original/avatar.jpg?1570217672","issuer-public-currency-holding-id":17,"burn-rate":500,"daily-burn-rate":"0.00014052","store-count":1,"listing-count":0,"product-count":1,"name":"Anza Coin","description":"Coins for my services","created-at":"2019-10-04T12:35:22.167-07:00","updated-at":"2019-10-04T12:35:22.167-07:00","get-icon-url":"/system/currencies/icons/000/000/010/original/currency.jpg?1570217722","number-of-reviews":0,"average-score":null,"public-amount-atomic":0,"public-currency-holding-id":null,"private-amount-atomic":0,"private-currency-holding-id":null,"total-amount-atomic":0,"number-of-burn-rate-changes":0,"number-public-currency-holdings":0,"next-daily-burn-amount":"0.0","timedate-of-last-private-tx":null,"amount-of-last-private-tx":null,"timedate-of-last-public-tx":null,"amount-of-last-public-tx":null,"private-burn-amount-atomic":0,"public-burn-amount-atomic":0,"total-burn-amount-atomic":0}}}')

FakeWeb.register_uri(:get, "https://api.mycurrency.com/authorized_currencies/10?state=post", body: '{"data":{"id":"10","type":"currencies","attributes":{"issuer-id":17,"issuer-user-id":17,"issuer-user-name":"Anza","issuer-user-avatar-url":"/system/users/avatars/000/000/017/original/avatar.jpg?1570217672","issuer-public-currency-holding-id":17,"burn-rate":500,"daily-burn-rate":"0.00014052","store-count":1,"listing-count":0,"product-count":1,"name":"Anza Coin","description":"Coins for my services","created-at":"2019-10-04T12:35:22.167-07:00","updated-at":"2019-10-04T12:35:22.167-07:00","get-icon-url":"/system/currencies/icons/000/000/010/original/currency.jpg?1570217722","number-of-reviews":0,"average-score":null,"public-amount-atomic":0,"public-currency-holding-id":null,"private-amount-atomic":66030000000000,"private-currency-holding-id":173,"total-amount-atomic":66030000000000,"number-of-burn-rate-changes":0,"number-public-currency-holdings":1,"next-daily-burn-amount":"9278535600.0","timedate-of-last-private-tx":"2020-03-31T21:26:38.425-07:00","amount-of-last-private-tx":66030000000000,"timedate-of-last-public-tx":null,"amount-of-last-public-tx":null,"private-burn-amount-atomic":0,"public-burn-amount-atomic":0,"total-burn-amount-atomic":0}}}')

FakeWeb.register_uri(:get, "https://api.mycurrency.com/authorized_currencies/100", body: '{"data":{"id":"100","type":"currencies","attributes":{"issuer-id":17,"issuer-user-id":17,"issuer-user-name":"Anza","issuer-user-avatar-url":"/system/users/avatars/000/000/017/original/avatar.jpg?1570217672","issuer-public-currency-holding-id":153,"burn-rate":500,"daily-burn-rate":"0.00014052","store-count":0,"listing-count":0,"product-count":0,"name":"Salutation Points","description":null,"created-at":"2020-03-15T02:48:40.261-07:00","updated-at":"2020-03-15T02:48:40.261-07:00","get-icon-url":"/system/currencies/icons/000/000/100/original/currency.jpg?1584265720","number-of-reviews":0,"average-score":null,"public-amount-atomic":0,"public-currency-holding-id":null,"private-amount-atomic":12054562806412,"private-currency-holding-id":163,"total-amount-atomic":12054562806412,"number-of-burn-rate-changes":0,"number-public-currency-holdings":1,"next-daily-burn-amount":"1693907165.55701424","timedate-of-last-private-tx":"2020-03-15T03:02:57.605-07:00","amount-of-last-private-tx":12080000000000,"timedate-of-last-public-tx":null,"amount-of-last-public-tx":null,"private-burn-amount-atomic":25437193588,"public-burn-amount-atomic":0,"total-burn-amount-atomic":25437193588}}}')

FakeWeb.register_uri(:get, "https://api.mycurrency.com/authorized_currencies/100?state=post", body: '{"data":{"id":"100","type":"currencies","attributes":{"issuer-id":17,"issuer-user-id":17,"issuer-user-name":"Anza","issuer-user-avatar-url":"/system/users/avatars/000/000/017/original/avatar.jpg?1570217672","issuer-public-currency-holding-id":153,"burn-rate":500,"daily-burn-rate":"0.00014052","store-count":0,"listing-count":0,"product-count":0,"name":"Salutation Points","description":null,"created-at":"2020-03-15T02:48:40.261-07:00","updated-at":"2020-03-15T02:48:40.261-07:00","get-icon-url":"/system/currencies/icons/000/000/100/original/currency.jpg?1584265720","number-of-reviews":0,"average-score":null,"public-amount-atomic":0,"public-currency-holding-id":null,"private-amount-atomic":12054562806412,"private-currency-holding-id":163,"total-amount-atomic":12054562806412,"number-of-burn-rate-changes":0,"number-public-currency-holdings":1,"next-daily-burn-amount":"1693907165.55701424","timedate-of-last-private-tx":"2020-03-15T03:02:57.605-07:00","amount-of-last-private-tx":12080000000000,"timedate-of-last-public-tx":null,"amount-of-last-public-tx":null,"private-burn-amount-atomic":25437193588,"public-burn-amount-atomic":0,"total-burn-amount-atomic":25437193588}}}')

FakeWeb.register_uri(:get, "https://api.mycurrency.com/authorized_currencies/101", body: '{"data":{"id":"101","type":"currencies","attributes":{"issuer-id":17,"issuer-user-id":17,"issuer-user-name":"Anza","issuer-user-avatar-url":"/system/users/avatars/000/000/017/original/avatar.jpg?1570217672","issuer-public-currency-holding-id":154,"burn-rate":0,"daily-burn-rate":"0.0","store-count":0,"listing-count":0,"product-count":0,"name":"Balloon Dollars","description":null,"created-at":"2020-03-15T02:51:10.562-07:00","updated-at":"2020-03-15T02:51:10.562-07:00","get-icon-url":"/system/currencies/icons/000/000/101/original/currency.jpg?1584265870","number-of-reviews":0,"average-score":null,"public-amount-atomic":0,"public-currency-holding-id":null,"private-amount-atomic":49080000000000,"private-currency-holding-id":174,"total-amount-atomic":49080000000000,"number-of-burn-rate-changes":0,"number-public-currency-holdings":1,"next-daily-burn-amount":"0.0","timedate-of-last-private-tx":"2020-03-31T22:53:27.347-07:00","amount-of-last-private-tx":49080000000000,"timedate-of-last-public-tx":null,"amount-of-last-public-tx":null,"private-burn-amount-atomic":0,"public-burn-amount-atomic":0,"total-burn-amount-atomic":0}}}')

FakeWeb.register_uri(:get, "https://api.mycurrency.com/authorized_currencies/101?state=post", body: '{"data":{"id":"101","type":"currencies","attributes":{"issuer-id":17,"issuer-user-id":17,"issuer-user-name":"Anza","issuer-user-avatar-url":"/system/users/avatars/000/000/017/original/avatar.jpg?1570217672","issuer-public-currency-holding-id":154,"burn-rate":0,"daily-burn-rate":"0.0","store-count":0,"listing-count":0,"product-count":0,"name":"Balloon Dollars","description":null,"created-at":"2020-03-15T02:51:10.562-07:00","updated-at":"2020-03-15T02:51:10.562-07:00","get-icon-url":"/system/currencies/icons/000/000/101/original/currency.jpg?1584265870","number-of-reviews":0,"average-score":null,"public-amount-atomic":0,"public-currency-holding-id":null,"private-amount-atomic":0,"private-currency-holding-id":null,"total-amount-atomic":0,"number-of-burn-rate-changes":0,"number-public-currency-holdings":0,"next-daily-burn-amount":"0.0","timedate-of-last-private-tx":null,"amount-of-last-private-tx":null,"timedate-of-last-public-tx":null,"amount-of-last-public-tx":null,"private-burn-amount-atomic":0,"public-burn-amount-atomic":0,"total-burn-amount-atomic":0}}}')

FakeWeb.register_uri(:get, "https://api.mycurrency.com/authorized_currencies/105", body: '{"data":{"id":"105","type":"currencies","attributes":{"issuer-id":17,"issuer-user-id":17,"issuer-user-name":"Anza","issuer-user-avatar-url":"/system/users/avatars/000/000/017/original/avatar.jpg?1570217672","issuer-public-currency-holding-id":160,"burn-rate":350,"daily-burn-rate":"0.000097604","store-count":0,"listing-count":0,"product-count":0,"name":"Alabama Coin","description":null,"created-at":"2020-03-21T20:14:52.023-07:00","updated-at":"2020-03-21T20:14:52.023-07:00","get-icon-url":"/system/currencies/icons/missing.png","number-of-reviews":0,"average-score":null,"public-amount-atomic":0,"public-currency-holding-id":null,"private-amount-atomic":0,"private-currency-holding-id":null,"total-amount-atomic":0,"number-of-burn-rate-changes":0,"number-public-currency-holdings":0,"next-daily-burn-amount":"0.0","timedate-of-last-private-tx":null,"amount-of-last-private-tx":null,"timedate-of-last-public-tx":null,"amount-of-last-public-tx":null,"private-burn-amount-atomic":0,"public-burn-amount-atomic":0,"total-burn-amount-atomic":0}}}')

FakeWeb.register_uri(:get, "https://api.mycurrency.com/authorized_currencies/105?state=post", body: '{"data":{"id":"105","type":"currencies","attributes":{"issuer-id":17,"issuer-user-id":17,"issuer-user-name":"Anza","issuer-user-avatar-url":"/system/users/avatars/000/000/017/original/avatar.jpg?1570217672","issuer-public-currency-holding-id":160,"burn-rate":350,"daily-burn-rate":"0.000097604","store-count":0,"listing-count":0,"product-count":0,"name":"Alabama Coin","description":null,"created-at":"2020-03-21T20:14:52.023-07:00","updated-at":"2020-03-21T20:14:52.023-07:00","get-icon-url":"/system/currencies/icons/missing.png","number-of-reviews":0,"average-score":null,"public-amount-atomic":0,"public-currency-holding-id":null,"private-amount-atomic":38340000000000,"private-currency-holding-id":175,"total-amount-atomic":38340000000000,"number-of-burn-rate-changes":0,"number-public-currency-holdings":1,"next-daily-burn-amount":"3742137360.0","timedate-of-last-private-tx":"2020-03-31T22:57:37.782-07:00","amount-of-last-private-tx":38340000000000,"timedate-of-last-public-tx":null,"amount-of-last-public-tx":null,"private-burn-amount-atomic":0,"public-burn-amount-atomic":0,"total-burn-amount-atomic":0}}}')

# https://api.mycurrency.com/currencies/<ID>
FakeWeb.register_uri(:get, "https://api.mycurrency.com/currencies/1", body: '{"data":{"id":"1","type":"currencies","attributes":{"issuer-id":3,"issuer-user-id":3,"issuer-user-name":"Kian","issuer-user-avatar-url":"/system/users/avatars/000/000/003/original/avatar.jpg?1568607042","issuer-public-currency-holding-id":1,"burn-rate":0,"daily-burn-rate":"0.0","store-count":0,"listing-count":0,"product-count":0,"name":"Kian Dollar","description":"The first currency created on MyCurrency\n! Check the creation date.","created-at":"2019-09-15T21:14:17.830-07:00","updated-at":"2019-09-16T19:38:19.756-07:00","get-icon-url":"/system/currencies/icons/000/000/001/original/currency.jpg?1568607257","number-of-reviews":0,"average-score":null,"user-is-active":true}}}')

FakeWeb.register_uri(:get, "https://api.mycurrency.com/currencies/2", body: '{"data":{"id":"2","type":"currencies","attributes":{"issuer-id":2,"issuer-user-id":2,"issuer-user-name":"Amin","issuer-user-avatar-url":"/system/users/avatars/000/000/002/original/avatar.jpg?1568543223","issuer-public-currency-holding-id":2,"burn-rate":700,"daily-burn-rate":"0.000198805","store-count":1,"listing-count":0,"product-count":1,"name":"Amin Credit","description":"one dollars worth of credit for purchases from my store","created-at":"2019-09-15T21:45:53.821-07:00","updated-at":"2020-03-15T01:41:03.937-07:00","get-icon-url":"/system/currencies/icons/000/000/002/original/currency.jpg?1584261663","number-of-reviews":0,"average-score":null,"user-is-active":true}}}')

FakeWeb.register_uri(:get, "https://api.mycurrency.com/currencies/3", body: '{"data":{"id":"3","type":"currencies","attributes":{"issuer-id":4,"issuer-user-id":4,"issuer-user-name":"Don","issuer-user-avatar-url":"/system/users/avatars/000/000/004/original/avatar.jpg?1568616946","issuer-public-currency-holding-id":3,"burn-rate":500,"daily-burn-rate":"0.00014052","store-count":1,"listing-count":0,"product-count":1,"name":"CryptoStore Dollars","description":"store credit for my crypto asset store","created-at":"2019-09-15T23:59:22.636-07:00","updated-at":"2019-09-15T23:59:22.636-07:00","get-icon-url":"/system/currencies/icons/000/000/003/original/currency.jpg?1568617162","number-of-reviews":0,"average-score":null,"user-is-active":true}}}')

FakeWeb.register_uri(:get, "https://api.mycurrency.com/currencies/4", body: '{"data":{"id":"4","type":"currencies","attributes":{"issuer-id":3,"issuer-user-id":3,"issuer-user-name":"Kian","issuer-user-avatar-url":"/system/users/avatars/000/000/003/original/avatar.jpg?1568607042","issuer-public-currency-holding-id":7,"burn-rate":0,"daily-burn-rate":"0.0","store-count":0,"listing-count":0,"product-count":0,"name":"USD Tracker","description":"Is worth exactly $1 USD","created-at":"2019-09-16T19:43:22.229-07:00","updated-at":"2019-09-16T19:43:22.229-07:00","get-icon-url":"/system/currencies/icons/000/000/004/original/currency.jpg?1568688202","number-of-reviews":0,"average-score":null,"user-is-active":true}}}')

FakeWeb.register_uri(:get, "https://api.mycurrency.com/currencies/10", body: '{"data":{"id":"10","type":"currencies","attributes":{"issuer-id":17,"issuer-user-id":17,"issuer-user-name":"Anza","issuer-user-avatar-url":"/system/users/avatars/000/000/017/original/avatar.jpg?1570217672","issuer-public-currency-holding-id":17,"burn-rate":500,"daily-burn-rate":"0.00014052","store-count":1,"listing-count":0,"product-count":1,"name":"Anza Coin","description":"Coins for my services","created-at":"2019-10-04T12:35:22.167-07:00","updated-at":"2019-10-04T12:35:22.167-07:00","get-icon-url":"/system/currencies/icons/000/000/010/original/currency.jpg?1570217722","number-of-reviews":0,"average-score":null,"user-is-active":true}}}')

FakeWeb.register_uri(:get, "https://api.mycurrency.com/currencies/100", body: '{"data":{"id":"100","type":"currencies","attributes":{"issuer-id":17,"issuer-user-id":17,"issuer-user-name":"Anza","issuer-user-avatar-url":"/system/users/avatars/000/000/017/original/avatar.jpg?1570217672","issuer-public-currency-holding-id":153,"burn-rate":500,"daily-burn-rate":"0.00014052","store-count":0,"listing-count":0,"product-count":0,"name":"Salutation Points","description":null,"created-at":"2020-03-15T02:48:40.261-07:00","updated-at":"2020-03-15T02:48:40.261-07:00","get-icon-url":"/system/currencies/icons/000/000/100/original/currency.jpg?1584265720","number-of-reviews":0,"average-score":null,"user-is-active":true}}}')

FakeWeb.register_uri(:get, "https://api.mycurrency.com/currencies/101", body: '{"data":{"id":"101","type":"currencies","attributes":{"issuer-id":17,"issuer-user-id":17,"issuer-user-name":"Anza","issuer-user-avatar-url":"/system/users/avatars/000/000/017/original/avatar.jpg?1570217672","issuer-public-currency-holding-id":154,"burn-rate":0,"daily-burn-rate":"0.0","store-count":0,"listing-count":0,"product-count":0,"name":"Balloon Dollars","description":null,"created-at":"2020-03-15T02:51:10.562-07:00","updated-at":"2020-03-15T02:51:10.562-07:00","get-icon-url":"/system/currencies/icons/000/000/101/original/currency.jpg?1584265870","number-of-reviews":0,"average-score":null,"user-is-active":true}}}')

FakeWeb.register_uri(:get, "https://api.mycurrency.com/currencies/105", body: '{"data":{"id":"105","type":"currencies","attributes":{"issuer-id":17,"issuer-user-id":17,"issuer-user-name":"Anza","issuer-user-avatar-url":"/system/users/avatars/000/000/017/original/avatar.jpg?1570217672","issuer-public-currency-holding-id":160,"burn-rate":350,"daily-burn-rate":"0.000097604","store-count":0,"listing-count":0,"product-count":0,"name":"Alabama Coin","description":null,"created-at":"2020-03-21T20:14:52.023-07:00","updated-at":"2020-03-21T20:14:52.023-07:00","get-icon-url":"/system/currencies/icons/missing.png","number-of-reviews":0,"average-score":null,"user-is-active":true}}}')

# if private currency holding id is 163, 173, 174 or 175, return true
FakeWeb.register_uri(:get, /https:\/\/api\.mycurrency\.com\/users\/165\/authorized_private_currency_holdings\/(163|173|174|175)\/pr_h_authentication_transaction\?amount=\d+&start_time=\d+/, body: '{"data":{"type":"transaction-authentication-status","attributes":{"transaction-authentication-status":true}}}')

# if private currency holding id is any number except 163, 173, 174 or 175, return false
FakeWeb.register_uri(:get, /https:\/\/api\.mycurrency\.com\/users\/#{A.microcurrency_deposit_user_id}\/authorized_private_currency_holdings(?!(?:\/163\/|\/173\/|\/174\/|\/175\/))\/\d+\/pr_h_authentication_transaction\?amount=\d+&start_time=\d+/, body: '{"data":{"type":"transaction-authentication-status","attributes":{"transaction-authentication-status":false}}}')

# FakeWeb.register_uri(:post, "https://api.mycurrency.com/users/#{A.microcurrency_deposit_user_id}/issuer/currencies/#{A.microcurrency_credit_currency_id}/stores/#{A.microcurrency_store_id}/products?currency_id_external_key=10", body: '{"data":{"id":"70","type":"products","attributes":{"sub-category-id":83,"sub-category-name":"MyCurrency currencies","currency-id":94,"currency-name":"MicroCurrency Credit","currency-icon-url":"/system/currencies/icons/missing.png","issuer-public-currency-holding-id":145,"days-to-cancellation":null,"minutes-to-cancellation":null,"store-id":60,"store-name":"MicroCurrency Store","product-name":"Credit for Anza Coin","product-description":"used by MicroCurrency companion app for internal operations to issue MyCurrency vouchers","price-cents":100,"active":true,"continued":true,"last-activated-at":"2020-03-15T02:44:40.106-07:00","created-at":"2020-03-15T02:44:40.106-07:00","updated-at":"2020-03-15T02:44:40.106-07:00","get-image-url":"/system/products/images/original/missing.png","owner-id":165,"owner-username":"MicroCurrency_Deposit","owner-avatar-url":"/system/users/avatars/original/missing.png"}}}', status: ["201", "201 Created"])

FakeWeb.register_uri(:post, "https://api.mycurrency.com/users/#{A.microcurrency_deposit_user_id}/issuer/currencies/#{A.microcurrency_credit_currency_id}/stores/#{A.microcurrency_store_id}/products?currency_id_external_key=101", body: '{"data":{"id":"72","type":"products","attributes":{"sub-category-id":83,"sub-category-name":"MyCurrency currencies","currency-id":94,"currency-name":"MicroCurrency Credit","currency-icon-url":"/system/currencies/icons/missing.png","issuer-public-currency-holding-id":145,"days-to-cancellation":null,"minutes-to-cancellation":null,"store-id":60,"store-name":"MicroCurrency Store","product-name":"Credit for Balloon Dollars","product-description":"used by MicroCurrency companion app for internal operations to issue MyCurrency vouchers","price-cents":100,"active":true,"continued":true,"last-activated-at":"2020-03-15T02:51:36.609-07:00","created-at":"2020-03-15T02:51:36.609-07:00","updated-at":"2020-03-15T02:51:36.609-07:00","get-image-url":"/system/products/images/original/missing.png","owner-id":165,"owner-username":"MicroCurrency_Deposit","owner-avatar-url":"/system/users/avatars/original/missing.png"}}}', status: ["201", "201 Created"])

FakeWeb.register_uri(:post, "https://api.mycurrency.com/users/#{A.microcurrency_deposit_user_id}/issuer/currencies/#{A.microcurrency_credit_currency_id}/stores/#{A.microcurrency_store_id}/products?currency_id_external_key=105", body: '{"data":{"id":"75","type":"products","attributes":{"sub-category-id":83,"sub-category-name":"MyCurrency currencies","currency-id":94,"currency-name":"MicroCurrency Credit","currency-icon-url":"/system/currencies/icons/missing.png","issuer-public-currency-holding-id":145,"days-to-cancellation":null,"minutes-to-cancellation":null,"store-id":60,"store-name":"MicroCurrency Store","product-name":"Credit for Alabama Coin","product-description":"used by MicroCurrency companion app for internal operations to issue MyCurrency vouchers","price-cents":100,"active":true,"continued":true,"last-activated-at":"2020-03-21T23:49:34.751-07:00","created-at":"2020-03-21T23:49:34.751-07:00","updated-at":"2020-03-21T23:49:34.751-07:00","get-image-url":"/system/products/images/original/missing.png","owner-id":165,"owner-username":"MicroCurrency_Deposit","owner-avatar-url":"/system/users/avatars/original/missing.png"}}}', status: ["201", "201 Created"])

RSpec.configure do |config|
  # ## Mock Framework
  #
  # If you prefer to use mocha, flexmock or RR, uncomment the appropriate line:
  #
  # config.mock_with :mocha
  # config.mock_with :flexmock
  # config.mock_with :rr

  # adding Warden - 10/29/2016
  config.include Devise::Test::ControllerHelpers, type: :controller

  # Remove this line if you're not using ActiveRecord or ActiveRecord fixtures
  config.fixture_path = "#{::Rails.root}/spec/fixtures"

  # If you're not using ActiveRecord, or you'd prefer not to run each of your
  # examples within a transaction, remove the following line or assign false
  # instead of true.
  config.use_transactional_fixtures = true

  # If true, the base class of anonymous controllers will be inferred
  # automatically. This will be the default behavior in future versions of
  # rspec-rails.
  config.infer_base_class_for_anonymous_controllers = false

  # Run specs in random order to surface order dependencies. If you find an
  # order dependency and want to debug it, you can fix the order by providing
  # the seed, which is printed after each run.
  #     --seed 1234
  config.order = "random"

  # RSpec Rails can automatically mix in different behaviours to your tests
  # based on their file location, for example enabling you to call `get` and
  # `post` in specs under `spec/controllers`.
  #
  # You can disable this behaviour by removing the line below, and instead
  # explictly tag your specs with their type, e.g.:
  #
  #     describe UsersController, :type => :controller do
  #       # ...
  #     end
  #
  # The different available types are documented in the features, such as in
  # https://relishapp.com/rspec/rspec-rails/v/3-0/docs
  config.infer_spec_type_from_file_location!

  Shoulda::Matchers.configure do |config|
		config.integrate do |with|
			# Choose a test framework:
			with.test_framework :rspec
			with.library :rails
		end
  end

  # Including to test requests
  config.include Request::JsonHelpers, :type => :controller
  config.include Request::HeadersHelpers, :type => :controller 
  config.include Devise::Test::ControllerHelpers, :type => :controller
  config.include EmailSpec::Helpers
  config.include EmailSpec::Matchers


  config.before(:each, type: :controller) do
	  include_default_accept_headers

    #WebMock.stub_request(:get, "").to_return(body: '')

    params = {:product=>{:sub_category_id=>A.currency_product_category_id.to_s, :product_name=>"Credit for Anza Coin", :product_description=>"used by MicroCurrency companion app for internal operations to issue MyCurrency vouchers", :active=>"true", :price_cents=>"100"}}

    WebMock.stub_request(:post, "https://api.mycurrency.com/users/#{A.microcurrency_deposit_user_id}/issuer/currencies/#{A.microcurrency_credit_currency_id}/stores/#{A.microcurrency_store_id}/products").with(body: params).to_return(body: '{"data":{"id":"70","type":"products","attributes":{"sub-category-id":83,"sub-category-name":"MyCurrency currencies","currency-id":94,"currency-name":"MicroCurrency Credit","currency-icon-url":"/system/currencies/icons/missing.png","issuer-public-currency-holding-id":145,"days-to-cancellation":null,"minutes-to-cancellation":null,"store-id":60,"store-name":"MicroCurrency Store","product-name":"Credit for Anza Coin","product-description":"used by MicroCurrency companion app for internal operations to issue MyCurrency vouchers","price-cents":100,"active":true,"continued":true,"last-activated-at":"2020-03-15T02:44:40.106-07:00","created-at":"2020-03-15T02:44:40.106-07:00","updated-at":"2020-03-15T02:44:40.106-07:00","get-image-url":"/system/products/images/original/missing.png","owner-id":165,"owner-username":"MicroCurrency_Deposit","owner-avatar-url":"/system/users/avatars/original/missing.png"}}}', status: [201, "201 Created"])

    params = {:product=>{:sub_category_id=>A.currency_product_category_id.to_s, :product_name=>"Credit for Salutation Points", :product_description=>"used by MicroCurrency companion app for internal operations to issue MyCurrency vouchers", :active=>"true", :price_cents=>"100"}}

    WebMock.stub_request(:post, "https://api.mycurrency.com/users/#{A.microcurrency_deposit_user_id}/issuer/currencies/#{A.microcurrency_credit_currency_id}/stores/#{A.microcurrency_store_id}/products").with(body: params).to_return(body: '{"data":{"id":"71","type":"products","attributes":{"sub-category-id":83,"sub-category-name":"MyCurrency currencies","currency-id":94,"currency-name":"MicroCurrency Credit","currency-icon-url":"/system/currencies/icons/missing.png","issuer-public-currency-holding-id":145,"days-to-cancellation":null,"minutes-to-cancellation":null,"store-id":60,"store-name":"MicroCurrency Store","product-name":"Credit for Salutation Points","product-description":"used by MicroCurrency companion app for internal operations to issue MyCurrency vouchers","price-cents":100,"active":true,"continued":true,"last-activated-at":"2020-03-15T02:49:24.764-07:00","created-at":"2020-03-15T02:49:24.764-07:00","updated-at":"2020-03-15T02:49:24.764-07:00","get-image-url":"/system/products/images/original/missing.png","owner-id":165,"owner-username":"MicroCurrency_Deposit","owner-avatar-url":"/system/users/avatars/original/missing.png"}}}', status: [201, "201 Created"])
  end

  config.before(:each, type: :model) do
    params = {:product=>{:sub_category_id=>A.currency_product_category_id.to_s, :product_name=>"Credit for Anza Coin", :product_description=>"used by MicroCurrency companion app for internal operations to issue MyCurrency vouchers", :active=>"true", :price_cents=>"100"}}

    WebMock.stub_request(:post, "https://api.mycurrency.com/users/#{A.microcurrency_deposit_user_id}/issuer/currencies/#{A.microcurrency_credit_currency_id}/stores/#{A.microcurrency_store_id}/products").with(body: params).to_return(body: '{"data":{"id":"70","type":"products","attributes":{"sub-category-id":83,"sub-category-name":"MyCurrency currencies","currency-id":94,"currency-name":"MicroCurrency Credit","currency-icon-url":"/system/currencies/icons/missing.png","issuer-public-currency-holding-id":145,"days-to-cancellation":null,"minutes-to-cancellation":null,"store-id":60,"store-name":"MicroCurrency Store","product-name":"Credit for Anza Coin","product-description":"used by MicroCurrency companion app for internal operations to issue MyCurrency vouchers","price-cents":100,"active":true,"continued":true,"last-activated-at":"2020-03-15T02:44:40.106-07:00","created-at":"2020-03-15T02:44:40.106-07:00","updated-at":"2020-03-15T02:44:40.106-07:00","get-image-url":"/system/products/images/original/missing.png","owner-id":165,"owner-username":"MicroCurrency_Deposit","owner-avatar-url":"/system/users/avatars/original/missing.png"}}}', status: [201, "201 Created"])

    params = {:product=>{:sub_category_id=>A.currency_product_category_id.to_s, :product_name=>"Credit for Salutation Points", :product_description=>"used by MicroCurrency companion app for internal operations to issue MyCurrency vouchers", :active=>"true", :price_cents=>"100"}}

    WebMock.stub_request(:post, "https://api.mycurrency.com/users/#{A.microcurrency_deposit_user_id}/issuer/currencies/#{A.microcurrency_credit_currency_id}/stores/#{A.microcurrency_store_id}/products").with(body: params).to_return(body: '{"data":{"id":"71","type":"products","attributes":{"sub-category-id":83,"sub-category-name":"MyCurrency currencies","currency-id":94,"currency-name":"MicroCurrency Credit","currency-icon-url":"/system/currencies/icons/missing.png","issuer-public-currency-holding-id":145,"days-to-cancellation":null,"minutes-to-cancellation":null,"store-id":60,"store-name":"MicroCurrency Store","product-name":"Credit for Salutation Points","product-description":"used by MicroCurrency companion app for internal operations to issue MyCurrency vouchers","price-cents":100,"active":true,"continued":true,"last-activated-at":"2020-03-15T02:49:24.764-07:00","created-at":"2020-03-15T02:49:24.764-07:00","updated-at":"2020-03-15T02:49:24.764-07:00","get-image-url":"/system/products/images/original/missing.png","owner-id":165,"owner-username":"MicroCurrency_Deposit","owner-avatar-url":"/system/users/avatars/original/missing.png"}}}', status: [201, "201 Created"])
  end
end

